stages:

  prepare:
    cmd: python -m src.data.prepare
    deps:
      - src/data/prepare.py
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - data.raw_path
          - data.target_column
          - data.drop_columns
          - data.random_seed
    outs:
      - data/processed/telco_churn_clean.csv

  preprocess:
    cmd: python -m src.data.preprocess
    deps:
      - src/data/preprocess.py
      - data/processed/telco_churn_clean.csv
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - preprocessing
          - data.target_column
          - data.random_seed
    outs:
      - data/processed/preprocessing_pipeline.joblib

  featurize:
    cmd: python -m src.features.featurize
    deps:
      - src/features/featurize.py
      - data/processed/telco_churn_clean.csv
      - data/processed/preprocessing_pipeline.joblib
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - data
          - preprocessing
          - monitoring.perturbation_features
          - monitoring.perturbation_std_multiplier
    outs:
      - data/splits/train.csv
      - data/splits/test.csv
      - data/splits/reference.csv
      - data/splits/production.csv

  train:
    cmd: python -m src.training.train
    deps:
      - src/training/train.py
      - data/splits/train.csv
      - data/splits/test.csv
      - configs/params.yaml
    params:
      - configs/params.yaml:
          - training
          - mlflow
          - data.random_seed
          - data.target_column
    outs:
      - mlflow.db
